<?php

namespace Visciukai\ImagesBundle\Entity;
use Visciukai\GalerijaBundle\Entity\Album;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $tag
     * @param Album $album
     *
     * @return Image[]
     */
    public function findByTags($tag, Album $album = null) {
        $rep = $this->getEntityManager()->getRepository($this->getEntityName());
        $queryBuilder = $rep->createQueryBuilder('i')
            ->select()
            ->leftJoin('i.tags', 't')
            ->where('t.name = :tag');

        if ($album !== null) {
            $queryBuilder->andWhere('i.album = :album')->setParameter('album', $album);
        }

        $queryBuilder->setParameter('tag', $tag);
        return $queryBuilder->getQuery()->execute();
    }
}
