<?php

namespace Visciukai\ImagesBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function handleTags($tagNames, Image $image) {
        $rep = $this->getEntityManager()->getRepository($this->getEntityName());
        $qb = $rep->createQueryBuilder('t')->delete()->where('t.image = :image')->setParameter('image', $image);

        if (!empty($tagNames)) {
            $qb->andWhere('t.name NOT IN (:tagNames)')->setParameter('tagNames', $tagNames);
        }

        $qb->getQuery()->execute();

        foreach ($image->getTags() as $currentTag) {
            if (in_array($currentTag->getName(), $tagNames)) {
                unset($tagNames[array_search($currentTag->getName(), $tagNames)]);
            }
        }

        foreach ($tagNames as $tag) {
            $newTag = new Tag();
            $newTag->setImage($image);
            $newTag->setName($tag);
            $this->getEntityManager()->persist($newTag);
        }
        $this->getEntityManager()->flush();
    }
}
