visciukai_logs_useraction:
    resource: "@VisciukaiLogsBundle/Resources/config/routing/useraction.yml"
    prefix:   /

visciukai_logs_uploaderror:
    resource: "@VisciukaiLogsBundle/Resources/config/routing/uploaderror.yml"
    prefix:   /uploaderror

visciukai_logs_searchentry:
    resource: "@VisciukaiLogsBundle/Resources/config/routing/searchentry.yml"
    prefix:   /searchentry
