fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

visciukai_logs:
    resource: "@VisciukaiLogsBundle/Resources/config/routing.yml"
    prefix:   /admin

visciukai_image:
    resource: "@VisciukaiImagesBundle/Resources/config/routing/image.yml"
    prefix:   /images

visciukai_galerija:
    resource: "@VisciukaiGalerijaBundle/Resources/config/routing.yml"
    prefix:   /


