
images_handle_tags:
    path:     /tags/{id}
    defaults: { _controller: "VisciukaiImagesBundle:Image:handleTags" }
    methods:  [POST, GET]

images_tag_action:
    path:     /tag/{albumId}
    defaults: { _controller: "VisciukaiImagesBundle:Image:tag", albumId: null }
    methods:  [GET]

images_make_cover_photo:
    path:     /cover/{id}
    defaults: { _controller: "VisciukaiImagesBundle:Image:makeCoverPhoto" }
    methods:  [POST, GET]

images:
    path:     /{albumId}
    defaults: { _controller: "VisciukaiImagesBundle:Image:index" }

images_show:
    path:     /{id}/show
    defaults: { _controller: "VisciukaiImagesBundle:Image:show" }

images_create:
    path:     /{albumId}/create
    defaults: { _controller: "VisciukaiImagesBundle:Image:create" }
    methods:  POST

images_edit:
    path:     /{id}/edit
    defaults: { _controller: "VisciukaiImagesBundle:Image:edit" }

images_update:
    path:     /{id}/update
    defaults: { _controller: "VisciukaiImagesBundle:Image:update" }
    methods:  [POST, PUT]

images_delete:
    path:     /{id}/delete
    defaults: { _controller: "VisciukaiImagesBundle:Image:delete" }
    methods:  [POST, DELETE, GET]
