visciukai_galerija_comment:
    resource: "@VisciukaiGalerijaBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

visciukai_galerija_homepage:
    path:     /
    defaults: { _controller: VisciukaiGalerijaBundle:Default:index }
