visciukai_galerija_comment:
    resource: "@VisciukaiGalerijaBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

visciukai_galerija_homepage:
    path:     /
    defaults: { _controller: VisciukaiGalerijaBundle:Default:index }

show_favourites:
    path:     /favourites/show
    defaults: { _controller: VisciukaiGalerijaBundle:Favourites:show }

add_favourite:
    path:     /favourites/add/{imageId}
    defaults: { _controller: VisciukaiGalerijaBundle:Favourites:add }

remove_favourite:
    path:     /favourites/remove/{imageId}
    defaults: { _controller: VisciukaiGalerijaBundle:Favourites:remove }
