uploaderror:
    path:     /
    defaults: { _controller: "VisciukaiLogsBundle:UploadError:index" }

uploaderror_show:
    path:     /{id}/show
    defaults: { _controller: "VisciukaiLogsBundle:UploadError:show" }



