comment:
    path:     /
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:index" }

comment_show:
    path:     /{imageId}/show
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:showImage" }

comment_new:
    path:     /{imageId}/new
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:new" }

comment_create:
    path:     /{imageId}/create
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:create" }
    methods:  POST

comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:edit" }

comment_update:
    path:     /{id}/update
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:update" }
    methods:  [POST, PUT]

comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:delete" }
    methods:  [POST, DELETE, GET]

comment_report:
    path:     /{id}/report
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:report" }
    methods:  GET