comment:
    path:     /
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:index" }

comment_show:
    path:     /{id}/show
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:show" }

comment_new:
    path:     /new
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:new" }

comment_create:
    path:     /create
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:create" }
    methods:  POST

comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:edit" }

comment_update:
    path:     /{id}/update
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:update" }
    methods:  [POST, PUT]

comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "VisciukaiGalerijaBundle:Comment:delete" }
    methods:  [POST, DELETE]
